site_name: Millennium Machines
repo_url: https://github.com/MillenniumMachines/Milo-v1.5
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - Sourcing Guide: bom/sourcing_guide.md
  - Printing Guide: printing/print_guide.md
  - Frequently Asked Questions: faq.md
  - Assembly Manual:
      - Acknowledgements: assembly_manual/chapters/acknowledgements.md
      - Introduction: assembly_manual/chapters/introduction.md
      - Hardware Reference: assembly_manual/chapters/hardware_reference.md
      - Y-Axis Assembly: assembly_manual/chapters/y_axis_assembly.md
      - X-Axis Assembly: assembly_manual/chapters/x_axis_assembly.md
      - Z-Axis Assembly: assembly_manual/chapters/z_axis_assembly.md
      - FMJ Assembly: assembly_manual/chapters/fmj_assembly.md
      - Table Assembly: assembly_manual/chapters/table_assembly.md
  - Electronics Manual:
      - Introduction: electronics_manual/chapters/introduction.md
      - Install RRF: electronics_manual/chapters/install_rrf.md
      - Assembly: electronics_manual/chapters/assemble_electronics.md
      - Pre-Flight Checks: electronics_manual/chapters/pre_flight_checks.md

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  font:
    text: Roboto
  icon:
    logo: fontawesome/solid/industry
    annotation: material/wrench-outline
  favicon: img/millennium-machines-icon.png
  palette:
    scheme: slate
    primary: red
    accent: custom

  features:
    - content.code.annotate
    - content.action.edit
    - navigation.tracking

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg